"use client";

import { Mail, ShieldCheck } from "lucide-react";
import type { InvitationListItem } from "@/lib/invitations/types";
import { formatDate, formatExpiry, getInitials } from "@/lib/invitations/utils";
import { ActionMenu } from "@/app/shared/ui/action-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, TableScroll } from "@/app/shared/ui/table";
import { InvitationStatusBadge } from "./invitation-status-badge";

type Props = { invitations: InvitationListItem[]; canResend: boolean; canRevoke: boolean; onView: (item: InvitationListItem) => void; onResend: (item: InvitationListItem) => void; onRevoke: (item: InvitationListItem) => void };

export function InvitationTable({ invitations, canResend, canRevoke, onView, onResend, onRevoke }: Props) {
  return <TableScroll><Table className="min-w-[900px]"><TableHeader><tr><TableHead>Invitee</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead>Sent</TableHead><TableHead>Expires</TableHead><TableHead className="w-16 text-right">Actions</TableHead></tr></TableHeader><TableBody>{invitations.map((invitation) => { const items = [{ label: "View invitation", onSelect: () => onView(invitation) }]; if (canResend && (invitation.status === "PENDING" || invitation.status === "EXPIRED")) items.push({ label: "Resend invitation", onSelect: () => onResend(invitation) }); if (canRevoke && invitation.status === "PENDING") items.push({ label: "Revoke invitation", danger: true, onSelect: () => onRevoke(invitation) }); return <TableRow key={invitation.id}><TableCell><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-700">{getInitials(invitation.name, invitation.email)}</div><div className="min-w-0"><p className="truncate font-semibold text-slate-950">{invitation.name || invitation.email}</p>{invitation.name && <p className="truncate text-xs text-slate-500">{invitation.email}</p>}</div></div></TableCell><TableCell><span className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-600"><ShieldCheck className="h-3.5 w-3.5 text-slate-400" />{invitation.roleName}</span></TableCell><TableCell><InvitationStatusBadge status={invitation.status} /></TableCell><TableCell><span className="inline-flex items-center gap-1.5 text-sm text-slate-600"><Mail className="h-3.5 w-3.5 text-slate-400" />{invitation.sendCount} {invitation.sendCount === 1 ? "time" : "times"}</span></TableCell><TableCell><p className="text-sm text-slate-600">{formatDate(invitation.expiresAt)}</p>{invitation.status === "PENDING" && <p className="mt-0.5 text-xs text-slate-400">{formatExpiry(invitation.expiresAt)}</p>}</TableCell><TableCell className="text-right"><ActionMenu label={`Actions for ${invitation.email}`} items={items} /></TableCell></TableRow>; })}</TableBody></Table></TableScroll>;
}
